//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyTool {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolyTool.common", typeof(common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All G.722.1 decoding has been completed.
        ///See the &apos;decoded.log&apos; for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllSiren14 {
            get {
                return ResourceManager.GetString("AllSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Wave encoding has been completed.
        ///See the &apos;encoded.log&apos; for details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllSiren14Enc {
            get {
                return ResourceManager.GetString("AllSiren14Enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsFormat {
            get {
                return ResourceManager.GetString("ColumnsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsName {
            get {
                return ResourceManager.GetString("ColumnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnsSize {
            get {
                return ResourceManager.GetString("ColumnsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Converted {
            get {
                return ResourceManager.GetString("Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Current version:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decoded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Decoded {
            get {
                return ResourceManager.GetString("Decoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decode error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DecodedError {
            get {
                return ResourceManager.GetString("DecodedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Encoded {
            get {
                return ResourceManager.GetString("Encoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoded error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncodedError {
            get {
                return ResourceManager.GetString("EncodedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///G.722.1 file decode failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSiren14 {
            get {
                return ResourceManager.GetString("ErrorSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///Wave file encode failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorWave {
            get {
                return ResourceManager.GetString("ErrorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The files exist in the specified folder.
        ///If you continue with the conversion, all files in the folder will be lost.
        ///Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExistWarning {
            get {
                return ResourceManager.GetString("ExistWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select save folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fbdSaveTitle {
            get {
                return ResourceManager.GetString("fbdSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select ITU G.722.1 Annex C (Polycom Siren14) folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fbdSiren14Title {
            get {
                return ResourceManager.GetString("fbdSiren14Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Wave folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fbdWaveTitle {
            get {
                return ResourceManager.GetString("fbdWaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File: &apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP: G.722.1 (*.unk)|*.unk;|IDOLM@STER DEARLY STARS: G.722.1 (*.s14;*.sss)|*.s14;*.sss|ITU G.722.1 Annex C (*.unk;*.s14;*.sss)|*.unk;*.s14;*.sss; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSiren14 {
            get {
                return ResourceManager.GetString("FilterSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDOLM@STER SP: G.722.1 (*.unk)|*.unk;|IDOLM@STER DEARLY STARS: G.722.1 (*.s14;*.sss)|*.s14;*.sss|ITU G.722.1 Annex C (*.unk;*.s14;*.sss; *.bnsf)|*.unk;*.s14;*.sss;*.bnsf|Container (*.nub2; *.nus3bank)|*.nub2;*.nus3bank; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSiren14_NU {
            get {
                return ResourceManager.GetString("FilterSiren14_NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Wave sound (*.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterWave {
            get {
                return ResourceManager.GetString("FilterWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BNSF (Bandai Namco Sound File: with Packed G.722.1 Annex C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatBNSF {
            get {
                return ResourceManager.GetString("FormatBNSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NUB2 Container (NUS3BANK Header File) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatNUB {
            get {
                return ResourceManager.GetString("FormatNUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NUS3BANK Container File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatNUS {
            get {
                return ResourceManager.GetString("FormatNUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S14 (Mono RAW G.722.1 File) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatS14 {
            get {
                return ResourceManager.GetString("FormatS14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSS (RAW G.722.1 File) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatSSS {
            get {
                return ResourceManager.GetString("FormatSSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UNK (RAW G.722.1 File) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatUNK {
            get {
                return ResourceManager.GetString("FormatUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave (Microsoft) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormatWAVE {
            get {
                return ResourceManager.GetString("FormatWAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ActivePerl found: &apos;{0}&apos;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundActivePerl {
            get {
                return ResourceManager.GetString("FoundActivePerl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strawberry Perl found: &apos;{0}&apos;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FoundStrawberryPerl {
            get {
                return ResourceManager.GetString("FoundStrawberryPerl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moved:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not verified: &apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotVerifyed {
            get {
                return ResourceManager.GetString("NotVerifyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open ITU G.722.1 Annex C (Polycom Siren14) File. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ofdSiren14Title {
            get {
                return ResourceManager.GetString("ofdSiren14Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Microsoft Wave sound File. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ofdWaveTitle {
            get {
                return ResourceManager.GetString("ofdWaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///Perl is not installed on this computer.
        ///ActivePerl or Strawberry Perl must be installed to use this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PerlError {
            get {
                return ResourceManager.GetString("PerlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Process ended.
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessEnd {
            get {
                return ResourceManager.GetString("ProcessEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application has been started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunningApp {
            get {
                return ResourceManager.GetString("RunningApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///waveheader.exe running...
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunningWH {
            get {
                return ResourceManager.GetString("RunningWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save ITU G.722.1 Annex C (Polycom Siren14) File. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sfdSiren14Title {
            get {
                return ResourceManager.GetString("sfdSiren14Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Microsoft Wave sound File. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sfdWaveTitle {
            get {
                return ResourceManager.GetString("sfdWaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G.722.1 file decode successed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessSiren14 {
            get {
                return ResourceManager.GetString("SuccessSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave file encode successed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessWave {
            get {
                return ResourceManager.GetString("SuccessWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thread completed.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThreadEnd {
            get {
                return ResourceManager.GetString("ThreadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred: &apos;{0}&apos;
        ///This file is not G.722.1.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedErrorNotSiren14 {
            get {
                return ResourceManager.GetString("UnexpectedErrorNotSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred: &apos;{0}&apos;
        ///This file is not Wave.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedErrorNotWave {
            get {
                return ResourceManager.GetString("UnexpectedErrorNotWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///G.722.1 file not found in the specified folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedErrorSiren14 {
            get {
                return ResourceManager.GetString("UnexpectedErrorSiren14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///Wave file not found in the specified folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedErrorWave {
            get {
                return ResourceManager.GetString("UnexpectedErrorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///The application can be updated. do you want to open the site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///The application is up to date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Uptodate {
            get {
                return ResourceManager.GetString("Uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verified: &apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Verifyed {
            get {
                return ResourceManager.GetString("Verifyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File: &apos;{0}&apos;
        ///Not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VGMError {
            get {
                return ResourceManager.GetString("VGMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
